name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Create .env file for cadv_api
        run: |
          mkdir -p secret
          echo "DBSTRING=postgres://cadvadmin:${{ secrets.DB_PASSWORD }}@${{ secrets.HOST }}:5432/cadvdb?sslmode=disable" >> secret/.env
          
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build&Push
        run: |
          docker build -f build/dockerfile -t cashadvisorbeta/cadv_sessions_cron:latest .
          docker push cashadvisorbeta/cadv_sessions_cron:latest